<?php
// Plugin definition
$plugin = array(
  'title' => t('Bootstrap Portfolio'),
  'category' => t('Columns: 1'),
  'icon' => 'bootstrap-portfolio.png',
  'theme' => 'bootstrap-portfolio',
  'css' => 'bootstrap-portfolio.css',
  'regions' => array(    
    'Principal' => t('Principal'),
    'Portfolio-1' => t('Portfolio 1'),
    'Portfolio-2' => t('Portfolio 2'),
    'Portfolio-3' => t('Portfolio 3'),
    'Portfolio-4' => t('Portfolio 4'),
    'Portfolio-5' => t('Portfolio 5'),
    'Portfolio-6' => t('Portfolio 6'),
    'Portfolio-7' => t('Portfolio 7'),
    'Portfolio-8' => t('Portfolio 8'),
    'Portfolio-9' => t('Portfolio 9'),
    'Portfolio-10' => t('Portfolio 10')
  ),
);
